### PR TITLE
Changes related to file system mount path

### PR DESCRIPTION
**Pull request by jayeshh123**
Changes related to file system mount path

### CODE REVIEW

**Comment by digvijay-ukirde** [comment]
@rajan-mis Changes are related to removing hardcoded file system mount to customer specific values.
Please review and let us know if you have any queries.

**Review by rajan-mis — COMMENTED** [review]
Where are we keeping this inventory. can you please confirm on this. 
`storage_cluster_filesystem_mountpoint`

**Comment by jayeshh123** [comment]
@rajan-mis We are keeping it in client inventory file: 

```
[root@jay-boot-tst-bootstrap ibm-spectrum-scale-install-infra]# cat client_inventory.ini 
[client_nodes]
jay-boot-tst-client-001.clntscale.com ansible_ssh_private_key_file=/opt/IBM/ibm-spectrumscale-cloud-deploy/client_key/id_rsa
[all:vars]
protocol_cluster_reserved_names = jay-boot-tst-ces.cesscale.com
storage_cluster_filesystem_mountpoint = /ibm/gpfs0/fs1
filesets = [{'name': 'data', 'mount_path': '/mnt/scale/data'}, {'name': 'tools', 'mount_path': '/mnt/scale/tools'}]
enable_ldap = false
ldap_basedns = null
ldap_server = null
ldap_admin_password = null
```

**Comment by rajan-mis** [comment]
> @rajan-mis We are keeping it in client inventory file:
> 
> ```
> [root@jay-boot-tst-bootstrap ibm-spectrum-scale-install-infra]# cat client_inventory.ini 
> [client_nodes]
> jay-boot-tst-client-001.clntscale.com ansible_ssh_private_key_file=/opt/IBM/ibm-spectrumscale-cloud-deploy/client_key/id_rsa
> [all:vars]
> protocol_cluster_reserved_names = jay-boot-tst-ces.cesscale.com
> storage_cluster_filesystem_mountpoint = /ibm/gpfs0/fs1
> filesets = [{'name': 'data', 'mount_path': '/mnt/scale/data'}, {'name': 'tools', 'mount_path': '/mnt/scale/tools'}]
> enable_ldap = false
> ldap_basedns = null
> ldap_server = null
> ldap_admin_password = null
> ```

@jayeshh123 Can you please add somewhere this information like readme or vars playbook because this is something exist within filesystem inventory or filesets inventoy. i will merge it for now. but we need to add this into the appropriate section inventory.

**Comment by jayeshh123** [comment]
@rajan-mis Sure I will raise another PR for it. Thank you

**Pull request merged**
