### PR TITLE
New role for remote mounted filesystem

### PR DESCRIPTION
**Pull request by olemyk**
This role adds support for consumers of the playbook to remote mount a IBM Spectrum Scale filesystem from a Storage cluster.  The roles leverage the Spectrum Scale REST API, meaning 5.0.5.2 or later versions of Scale contains the endpoints.
Role support also If Accessing/Client Cluster don`t have GUI. 

Please check the ReadMe for more information

### CODE REVIEW

**Comment by rajan-mis** [comment]
@olemyk Thanks for adding this role. other component team is also looking for this to integrate.

It looks good to me , do you think we should change variable name , register name to starts with scale_

**Comment by olemyk** [comment]
Like this:?

```
 scale_client_cluster_gui_username:
 scale_client_cluster_gui_password: 
 scale_client_cluster_gui_hostname: 
 scale_client_cluster_filesystem_name: 
 scale_client_cluster_remotemount_path: 
 scale_storage_cluster_gui_username: 
 scale_storage_cluster_gui_password: 
 scale_storage_cluster_gui_hostname: 
 scale_storage_cluster_filesystem_name: 
```
I would guess this would be to long? 
scale_remotemount_client_cluster_gui_username:

**Comment by rajan-mis** [comment]
> Like this: @rajan-mis
> 
> ```
>  scale_client_cluster_gui_username:
>  scale_client_cluster_gui_password: 
>  scale_client_cluster_gui_hostname: 
>  scale_client_cluster_filesystem_name: 
>  scale_client_cluster_remotemount_path: 
>  scale_storage_cluster_gui_username: 
>  scale_storage_cluster_gui_password: 
>  scale_storage_cluster_gui_hostname: 
>  scale_storage_cluster_filesystem_name: 
> ```
> 
> I would guess this would be to long?
> `scale_remotemount_client_cluster_gui_username:`

Yes @olemyk . @acch is suggesting to use variable name should start with scale_

Yes agree. its long one. 

Can we change it to some thing,
` scale_remotemount_client_gui_username:`

**Comment by olemyk** [comment]
Sound good, will change the variables.

What about naming for Client Cluster and Storage cluster? @rajan-mis 
- Client Cluster: could also be "Accessing"  or "Remote" Cluster  
- Storage Cluster: could also be "Owning" cluster.

Personally, I like the Client or Remote cluster and  Storage cluster, I think that is easier for people to understand.

**Comment by rajan-mis** [comment]
> Sound good, will change the variables to something simlliar as ´scale_remotemount_client_gui_username:´
> 
> What about naming for Client Cluster and Storage cluster? @rajan-mis
> 
>     * Client Cluster: could also be "Accessing"  or "Remote" Cluster
> 
>     * Storage Cluster: could also be "Owning" cluster.
> 
> 
> Personally, I like the Client or Remote cluster and Storage cluster, I think that is easier for people to understand.

Thanks @olemyk . That looks good. Thank you

**Comment by olemyk** [comment]
Updated the variables  @rajan-mis 


```
scale_remotemount_client_gui_username:
scale_remotemount_client_gui_password:
scale_remotemount_client_gui_hostname:
scale_remotemount_client_filesystem_name:
scale_remotemount_client_remotemount_path:
scale_remotemount_storage_gui_username:
scale_remotemount_storage_gui_password:
scale_remotemount_storage_gui_hostname:
scale_remotemount_storage_filesystem_name:
scale_remotemount_debug: 
scale_remotemount_forceRun: 
scale_remotemount_access_mount_attributes:
scale_remotemount_client_no_gui: 
scale_remotemount_storage_pub_key_location:
scale_remotemount_cleanup_remote_mount: 
```

**Review by rajan-mis — APPROVED** [review]
@olemyk Thanks for adding this role.

**Pull request merged**
