### PR TITLE
Improve daemon state support

### LINKED ISSUE #294: Variable 'state' is mandatory but no default provided
With the changes to `roles/core/cluster_start.yml` (6449a133857be8540d4d3b8f4fd1d47f50ed43ac) we've introduced the possibility to set the 'state' of a node. GPFS will not be started if 'state' is 'maintenance'. However, the changes make 'state' a mandatory variable, GPFS will not be started if it's undefined and subsequent tasks will fail if GPFS is not acitve (e.g. creating filesystem). There are a few problems with that:

- The fact that 'state' is a mandatory variable isn't documented
- The name of the variable doesn't follow our convention - there are likely going to be name collisions
- It is unclear which value should be applied to 'state' for making the roles start GPFS after installation (most common case, I guess)

I will look into this and propose some changes. Will submit a PR when ready.

### PR DESCRIPTION
**Pull request by acch**
Fixes #294:

- Provide default value (make variable optional)
- Don't add `absent` nodes to cluster
- Add documentation
- Raname variable to adhere with naming convention
- Fix formatting and improve wording
- Fix typos

### CODE REVIEW

**Comment by acch** [comment]
I'm done testing, PR is ready. Note that the variable name has changed from `state` to `scale_daemon_state`. This means that users relying on the functionality need to adapt their definitions...

**Comment by rajan-mis** [comment]
@acch Thanks. Muthu is still thinking if we can keep `state` instead of `scale_state` similar to ansible state variable.  else we can merge this PR.

**Comment by acch** [comment]
@mamuthiah I really don't like the name `state` - here are a couple of reasons:
- Searching for `state` in the code gives me 65 results in the core component alone. Since almost every module has a `state` parameter it's very difficult to find the spots where our variable is being used...
- Variables without a `scale_` prefix are likely being used in other context as well. Users might define their own local variables with that name, which would result in collisions (very hard to debug)...
- The name would be inconsistent with all of the other variable names which users have to define (`scale_version`, `scale_cluster_clustername`, `scale_install_repository_url`)...

What's the advantage of omitting the `scale_` prefix in this case?

**Review by rajan-mis — APPROVED** [review]
Looks good to me. Thanks @acch

**Pull request merged**
