### PR TITLE
Add a role under the core roles to assist remote mount a spectrum scale filesystem

### PR DESCRIPTION
**Pull request by whowutwut**
This role adds support for consumers of the playbook to remote mount a IBM Spectrum Scale filesystem from a Storage cluster.  The roles leverage the Spectrum Scale REST API , meaning 5.0.5.2 or later versions of Scale contains the endpoints. 

The following variables would need to be defined by the user, either as vars to calling the role in collections,  or in `group_vars/all`.   The precheck.yml will fail the role if these attributes are not defined. 

```yaml
## remote mount variables (edit and match to your environment)
# client_gui_user: user
# client_gui_password: passw0rd
# client_cluster_ip: client-cluster.example.com
# client_filesystem_name: fs1
# client_remotemount_path: "/mnt/{{ client_filesystem_name }}"
# storage_gui_user: "{{ client_gui_user }}"
# storage_gui_password: "{{ client_gui_password }}"
# storage_cluster_ip: storage-cluster.example.com
# storage_filesystem_name: fs1
```

### CODE REVIEW

**Comment by whowutwut** [comment]
Please do not merge this, it's WIP for now, i may need to make some fixes to this PR as we start to exercise it.

**Comment by rajan-mis** [comment]
As we are using GUI rest api for remote mount execution and i think this require gui node as well , if so then should the remote_mount role be in the core role or it should go under gui role ?

**Comment by whowutwut** [comment]
@rajan-mis You bring up an excellent comment!  To answer this, I think we have to consider how these roles are intended or other possible ways that they could be consumed by the end users.      I think in the current implementation of the use case from this repo's point of view, there's an assumption that the end user will clone and execute playbook.yaml and the ordering of the play execution is driven purely from running **playbook.yaml**.  

But let me throw out two cases that I can think about right now: 
* Could the user, instead of itemizing the roles in playbook.yaml, call a single role that will pull in the other roles as dependencies and get the same effect at the end? 
* What if the user already is running an ansible-playbook and wants to call these roles as part of that, instead of spawning another process of `ansible-playbook`? 

In the use case I'm currently exercising, we are picking and choosing roles to execute.  _I think..._ something like galaxy and collections allows for running roles independent of each other.  _I think._  (I have no actually  real world experience consuming roles in galaxy at this time)

Getting back to your question, if remote mount is a  "core" function, i think it should go into the core sub-directory.  The role is written in such a way that if it cannot communicate with the REST endpoint, it will just fail at that point..    I don't intend for this role to be added to playbook.yaml .. and would expect the user to call it as needed. (after the GUI is already up) or in a task after the GUI is up.

**Comment by whowutwut** [comment]
Replaced by #315

**Pull request closed without merging**
