### PR TITLE
Improve check for gpgcheck value for yum repos

### PR DESCRIPTION
**Pull request by acch**
Only test once if gpgcheck is necessary (prior to Scale version 5.0.4), and then re-use variable.
Also, make variable follow naming convention.

### CODE REVIEW

**Comment by rajan-mis** [comment]
@acch Are you planning to set  this fact i.e `scale_install_gpgcheck` in some common file .

**Comment by acch** [comment]
Currently the variable `scale_install_gpgcheck` is set in `core/node/tasks/install_repository.yml`, which is where it's being used first. As the var is specific to the repository installation method I guess that this is the right spot... or do you have another suggestion?

The variable `scale_install_disable_gpgcheck`, which applies to all installation methods, is set in `core/node/tasks/yum/install.yml`. Does that sound right?

**Comment by rajan-mis** [comment]
@acch Thanks. i was thinking if we can set it to some common place like core/common  . so that we can run other role without core/node role too.

**Comment by acch** [comment]
That sounds like a good idea - moved to `core/common`:
```
- name: check | Disable gpg check (prior to version 5.0.4.0)
  set_fact:
    scale_install_gpgcheck: "{{ false if scale_version is version_compare('5.0.4', '<') else true }}"
    scale_install_disable_gpgcheck: "{{ true if scale_version is version_compare('5.0.4', '<') else false }}"
```

**Comment by acch** [comment]
Replaced by #468

**Pull request closed without merging**
