### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by acch**
I've made some (minor) changes to the README:
- Consistent formatting
- Syntax Highlighting 
- GPFS → Spectrum Scale
- Table of Contents

Nothing serious, but I wanted to make sure I understand the process before getting my hands dirty ;-)
Please let me know what you think - Cheers!

### CODE REVIEW

**Comment by acch** [comment]
I've signed-off my commits now and force-pushed them once more. Thanks @whowutwut for pointing this out!

**Comment by rajan-mis** [comment]
@acch Thanks for making this change. i started looking through your change .

**Comment by acch** [comment]
Thanks @rajan-mis - I appreciate your time. If you have any comments please let me know and I'll make further changes to incorporate your feedback.

If you agree with the changes then I'd suggest to merge them but leave this PR open, so that I can add further commits to it later. I have some additional improvements on my list which I'd like to apply to the documentation...

Thanks and all the best!

**Comment by rajan-mis** [comment]
@acch it looks good to me.  we can merge this in the dev branch. Thank you

**Pull request merged**
