### PR TITLE
Development staging ==> dev

### PR DESCRIPTION
**Pull request by rajan-mis**
Development staging ==> dev

This PR will consider below mentioned features,

README enhancement.
Code refactor to support multiple operating system ( RHEL, UBUNTU and SLES)
Callhome role
SMB and NFS protocol support
ECE installation and configuration support
HPT installation and  configuration support

### CODE REVIEW

**Review by acch — COMMENTED** [review]
That's a pretty big PR with 250 changed files... I'm not quite sure what I am supposed to review?

**Comment by rajan-mis** [comment]
@acch Thanks. This PR contains our all development_staging branch features development code. Here we are merging complete branch from devlopment_staging ===> dev . so i am not sure if we can create multiple PR from this.

**Comment by rajan-mis** [comment]
Jenkins JOB result:

```
PLAY RECAP *********************************************************************
test-vm1             : ok=329  changed=51   unreachable=0    failed=0    skipped=326  rescued=0    ignored=3   
test-vm3             : ok=191  changed=22   unreachable=0    failed=0    skipped=213  rescued=0    ignored=2   
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
Tuesday 17 November 2020  02:57:04 -0700 (0:00:00.041)       0:15:25.812 ****** 
=============================================================================== 
core/cluster : wait-daemon-active ------------------------------------- 129.37s
gui/cluster : configure | Initialize the GUI --------------------------- 88.18s
scale_fileauditlogging/node : install | Install GPFS file audit logging packages -- 68.24s
smb/cluster : configure | Enable SMB ----------------------------------- 42.69s
core/node : install | Install GPFS packages ---------------------------- 39.32s
gui/cluster : configure | Start and enable GUI service ----------------- 38.97s
core/node : build | Compile GPL module --------------------------------- 33.90s
smb/node : install | Install GPFS SMB packages ------------------------- 33.39s
core/cluster : storage | Wait for NSD configuration to be synced across cluster -- 30.70s
nfs/common : configure | Enabling CES ---------------------------------- 27.24s
nfs/node : install | Install GPFS nfs packages ------------------------- 25.53s
nfs/common : configure | Assign export ips as pool --------------------- 18.78s
scale_fileauditlogging/cluster : configure | configure file audit logging -- 18.69s
gui/node : install | Install GPFS GUI packages ------------------------- 17.59s
callhome/cluster : configure | Create callhome group ------------------- 17.33s
nfs/common : configure | Configuring cesSharedRoot --------------------- 11.14s
nfs/cluster : configure | Enable NFS ----------------------------------- 10.95s
nfs/common : configure | Setting server licenses on protocol nodes ----- 10.20s
nfs/cluster : configure | Configuring NFS performance monitoring sensors -- 10.05s
smb/cluster : configure | Configuring SMB performance monitoring sensors --- 9.49s
Playbook run took 0 days, 0 hours, 15 minutes, 25 seconds
```

**Comment by acch** [comment]
Sure - doesn't make sense to split this one up. Looks good!

Now that we've merged `development_staging` into `dev`, does that mean that all future PRs should go to `dev` instead? If yes then I'd suggest to delete `development_staging` to avoid confusion...

**Pull request merged**
