### PR TITLE
New developed features code

### PR DESCRIPTION
**Pull request by rajan-mis**
Ansible support code for 

- Ubuntu operating system
- SLES 15 support code
- Callhome improvement
- CES support
- NFS support
- SMB support
- Multiple refactor

### CODE REVIEW

**Comment by acch** [comment]
Allow me to add a few comments:

- That's a pretty big PR. 160 changed files are hard to digest... It's difficult to understand what (side-)effect the individual changes have - and the commit messages don't really help either. I'd suggest to break large refactorings up into multiple PRs which can be assessed individually.

- Commits to dev/master should not include any lines which are commented out (e.g. `roles/callhome/cluster/defaults/main.yml`, `roles/callhome/cluster/tasks/configure.yml`). Similarly, any `# TODO` comments should be removed prior to a commit.

- Not sure about our policy regarding `debug` tasks... I'd say that those shouldn't make it into production either.

- I'd suggest to consistently prefix all variables registered with the`set_fact` task with `scale_*` to avoid collisions. Also, this notation makes it clear that this is a custom variable, rather than one which is gathered automatically by `ansible_*`. Variables without a prefix should only be used as temporary `vars:` within a single task.

- I'd suggest not to mix hard-coded strings with those defined in variables. I like the idea of defining e.g. distros and package names in variables (`roles/.../vars/main.yml`). But if we do, then we should do it consistently for all options:

   ```yaml
   # roles/core/node/tasks/build.yml
    - name: build | Identify RedHat distribution
      set_fact:
        scale_build_distribution: REDHAT_AS_LINUX
      when:
        ansible_distribution == 'CentOS' or
        ansible_distribution == 'RedHat' or
        ansible_distribution in scale_sles_distribution
   ```

- There seems to be a global (string) replace of the term _RPM_ with the term _package_. That's valid in most cases, but not in all cases. For example, the path is:
   ```
   /usr/lpp/mmfs/.../gpfs_rpms/
   ```
   (no 'package' in there)

- Variables which are meant to be changed by the user should go into `roles/.../defaults/main.yml`. This indicates that users are welcome to override those definitions.

   Variables which are _not_ meant to be changed by the user should go into `roles/.../vars/main.yml` (similar to constants in other languages). Examples for those vars are directories which hardly ever change, such as `/usr/lpp/mmfs/bin/`. Similarly, package names hardly change and should go into `vars/main.yml` rather than `defaults/main.yml`.

- I'm not sure if it's a good idea to create separate `README` for each of the roles. I'd suggest to:
  - Stick to a consistent, case-sensitive name (don't mix `Readme.md` and `README.md`)
  - If there are further docs describing individual components / roles in greater detail then link to them from the main `README.md`

- Roles can not have their own license definition (e.g. `roles/ntp/README.md`). All code _must_ adhere to the project's license, which is Apache2.

- Commits need to be [signed](https://github.com/IBM/ibm-spectrum-scale-install-infra/blob/dev/CONTRIBUTING.md#sign-your-work-for-submittal) to accept the DCO.

**Comment by rajan-mis** [comment]
@acch Thanks for your review comment.   

We have mainly added  multiple os support  like Ubuntu 16 , Ubuntu18 , Ubuntu 20 , SLES 12 and SLES 15 . so i tried to refactor as much as possible to remove  os dependency code and we will have to do for all supported component what we have in the open source GIT branch .

Other large code change is for  new component support.  we have written proper design doc for all new role . please let me know what is the best way to share design doc. 

I will try to incorporate these review comments.  Thank you.

**Comment by rajan-mis** [comment]
I started incorporating @acch review comments and we discussed . i am planning to break this PR into 2. 

1.  PR for multiple os support
2.  CES role support

**Comment by rajan-mis** [comment]
I discussed with @acch  and we decided to create 2 separate PR i.e 1. for multiple OS support and 2. for CES support. 

I also tried to incorporate review comment in the newly created PR.

https://github.com/IBM/ibm-spectrum-scale-install-infra/pull/203.

So i am closing this pull request.

**Pull request closed without merging**
