### PR TITLE
[Suggestion] ansible-galaxy collections support 

### PR DESCRIPTION
**Pull request by whowutwut**
This PR replaces #106 

```release-notes
- Create galaxy.yml
- Add requirements.yml to show we have no external dependencies (to run the roles)
- Move custom_modules role to standard ansible layout (plugins)
```

This converts the entire project to support ansible-galaxy collections which comes with some changes in how we are currently used to deploying. 

* the repo is no longer "cloned" down but rather the roles/playbooks/etc are install via a collections.tar.gz file 
* on each release, we should build this tar.gz and attach it to the github release page, customers can now download instead of clone
* collections can be installed in default location, or in relative path 
* to call the roles, the playbook.yml file would need to be modified to import the collections , then call the roles

Just opening this for suggestion so the team can see the changes. 

We still have to discuss the logistics of how or whether this would be accepted to the upstream project

### CODE REVIEW

**Comment by whowutwut** [comment]
With the rename of #175, I started this PR again from scratch and force pushed the changes from https://github.com/whowutwut/ibm-spectrum-scale-install-infra/tree/collection_support into this PR branch.. so that I don't have to delete/re-create it.

**Comment by rajan-mis** [comment]
@whowutwut  currently we support role based implementation for cloud deployment if we will merge this collection code then it may fail for role based execution. 

I am thinking , can we create one new branch for CNSS BETA and will merge this code there and CNSS team can utilize this functionality from  newly created branch instead of master/dev.

**Comment by whowutwut** [comment]
@rajan-mis Thanks! yes..  I did considered this, but the flip side to this is how would we maintain these branches while they existed...   I do think that this would probably be the best option going forward...  but I worry that it will never go into dev. 

Right now, we have dev/master and dev periodically gets merged to master.  This same thing would apply to the more branches that we had,  like python3 branch.  I think right now, I am owning the merge of dev -> python3 (like when the naming of the modules changes)  This would also happen on the collections branch.  

Also changes right now are going into dev, so each change that I need, I would have to cherry-pick that into collection, or periodically (monthly) merge it to collections (depending on how urgent of a fix it is)  But seems like a lot of overhead. 

Let me think about it some more, maybe look to doing somthing in August. The way I am pulling down the changes to cnss is also not easy to maintain.

**Comment by acch** [comment]
Let me add my thoughts to the discussion:

- Publishing this project on Galaxy is definitely the right thing to do in the long-term. Users typically prefer running `ansible-galaxy install` over `git clone`, and for various reasons.

- My understanding is that Galaxy supports both, roles and collections. I personally have experience publishing [roles](https://galaxy.ansible.com/acch/spectrum_scale), but not collections.

- My understanding is that collections are a superset, while roles are a subset. Collections can contain roles, along with modules/plugins/etc. — hence, my understanding is that we can publish the project as a collection (given the correct `galaxy.yml` and dir-structure) and users can continue to use it for their role-based workflow. I don't think collections and roles are mutually exclusive.

BTW: I have most of my knowledge on collections from this blog post:
https://www.ansible.com/blog/the-future-of-ansible-content-delivery

> ...As you can see, this structure does look very similar to roles. There are some slight differences though...

**Comment by acch** [comment]
I did some more research on this subject. There is a pretty comprehensive [Developer Guide](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html) available which answers most questions.

Collections (must) follow this dir structure: (here's an [example boilerplate](https://github.com/bcoca/collection))
```
collection/
├── docs/
├── galaxy.yml
├── plugins/
│   ├── modules/
│   │   └── module1.py
│   ├── inventory/
│   └── .../
├── README.md
├── roles/
│   ├── role1/
│   ├── role2/
│   └── .../
├── playbooks/
│   ├── files/
│   ├── vars/
│   ├── templates/
│   └── tasks/
└── tests/
```

I agree with moving `custom_modules` to `plugins/`. I would also suggest moving `playbook.yml` to `playbooks/`, and also moving the roles out of subdirectories into a single, flat `roles/` dir.

Note that with collections the role's metadata (`meta/main.yml`) is ignored. Instead, metadata is defined globally in `galaxy.yml` and the value of *role_name* is simply taken from the dir name. Hence, we'll need to rename the role dirs to allow for Galaxy publication. Each role must reside in a dir with a unique name.

Last but not least: it appears to me that Content Collections are clearly the strategic direction going forward for making content available to other Ansible users. There's already a rich set of content for other [IBM products](https://galaxy.ansible.com/ibm). [Here's](https://galaxy.ansible.com/ibm/ibm_zos_zosmf) a particularly good example which we can learn from (and adopt) — combining multiple modules, roles and plugins into a single, well-structured collection.

**Comment by acch** [comment]
This is an older issue - migrating to Ansible Galaxy is a long-term goal of this project. Lots of changes have been implemented already (e.g. #570 and #572), and overall progress is now being tracked in #247.

Hence, I'd suggest to close this PR - OK?

**Comment by whowutwut** [comment]
Makes sense.. Yea, let's close it.

**Pull request closed without merging**
