### PR TITLE
CES fix for nextgen

### PR DESCRIPTION
**Pull request by rajan-mis**
Signed-off-by: Rajan Mishra rajanmis@in.ibm.com

### CODE REVIEW

**Comment by acch** [comment]
Thanks @rajan-mis. I see that you've added code to define `scale_daemon_nodename` and `scale_admin_nodename` in the `ces_common` role - what's the rationale behind this? Is the variable used anywhere (not included in this PR)?

**Comment by rajan-mis** [comment]
@acch This was failing due to the `scale_daemon_nodename` name was with `ansible hostnam`e and we are checking condition with inventory hostname. i am thinking to add this into the  core_common role because we are also using this in the core_configure role. please let me know your suggestion.  Thanks

**Comment by rajan-mis** [comment]
@acch As we are checking everything through `inventory_hostname` , so can we change default to` inventory_hostname `instead of` ansible_hostname`  then we don't need to define this, `scale_daemon_nodename` and `scale_admin_nodename` . i will also check .  Thanks

**Comment by acch** [comment]
No matter what we define as default for `scale_daemon_nodename`, as this is a variable our users could always override it and set any arbitrary string. We can't rely on any particular value. Hence, we'll always need to check against the appropriate value:

- If the list is produced by `mm...` command then we should check against `scale_daemon_nodename`
- If the list is produced within the playbooks (e.g. through `add_host` tasks) then we should check against `inventory_hostname`

**Pull request merged**
